### ISSUE TITLE
Auditor verify not working

### ISSUE THREAD

**Issue by laserguy** [walt-id/waltid-ssikit#201]
Environment: Docker Desktop with WSL

I'm using the generally available rest-apis on `https://docs.walt.id/v/ssikit/getting-started/rest-apis` 

### ISSUE

I'm using the below API and get the below error.
![image](https://user-images.githubusercontent.com/8339759/206175112-f70a9c22-bdbc-4e4c-8038-31d1dbd87978.png)

The file below contains the  **request_body**, I tried with both **VC** and **VP** in the **credentials**.
and I'm using the format as per `https://docs.walt.id/v/ssikit/getting-started/rest-apis/auditor-api`
[vc.txt](https://github.com/walt-id/waltid-ssikit/files/10175925/vc.txt)

### WHAT ELSE I TRIED (This lead to other issues)

I tried core API  https://core.ssikit.walt.id/v1/vc/verify to verify it, and it works fine, but I can't apply a policy here.

**I tried CLI as well...**

See the output of the below commands

- **ssikit did list**

walt.id SSI Kit 1.13.0-SNAPSHOT (running on Java 19.0.1+10)

Listing DIDs...

Results:

1: did:key:z6MkrNhdvrsyBUSsioTnbr9W1iJGT49XxpoNQgShRCqfUmWM
2: did:key:z6MkiFRREdnq6wcDoHA4cYnavgXfG9s9sJY8pTrxX9cuWdro

- **ssikit vc issue -i did:key:z6MkrNhdvrsyBUSsioTnbr9W1iJGT49XxpoNQgShRCqfUmWM -s did:key:z6MkiFRREdnq6wcDoHA4cYnavgXfG9s9sJY8pTrxX9cuWdro -t VerifiableId temp.json**

Output in file:  [temp.txt](https://github.com/walt-id/waltid-ssikit/files/10175996/temp.txt)

`It says saved to file temp.json, but this file doesn't exist anywhere. I checked the data folder and everywhere else still couldn't find it.`
Therefore I copied and pasted the generated credentials into a file and ran below command

- **ssikit vc verify temp.json**

walt.id SSI Kit 1.13.0-SNAPSHOT (running on Java 19.0.1+10)

Verifying from file "temp.json"...

Could not load file: "temp.json".

`I tried giving the full path of the file, still it doesn't work`

**Comment by severinstampler** [comment]
Hi @laserguy 
Regarding the first issue, via the verify REST API: The deployment of ssikit has recently been updated to a newer version, which currently doesn't support the JsonSchemaPolicy anymore, only the TrustedSchemaRegistryPolicy is supported in this build.
So your problem is caused by the ssikit trying to load the missing policy. If you just remove the "JsonSchemaPolicy" entry from the policies in your request body, the verification works.

Regarding the issue with CLI: I presume your ssikit command runs the docker container, right? If so, the file is probably written inside the container on it's temporary in-memory filesystem. So you won't find it in your host filesystem.
In order to write the file using the docker image, you would need to mount a volume that maps to a folder on your local filesystem and specify the full path inside the container as a save file name.

**Comment by severinstampler** [comment]
I just looked up the docker command in the ssikit documentation:
`alias ssikit="docker container run -p 7000-7004:7000-7004 -itv $(pwd)/data:/app/data docker.io/waltid/ssikit"`

This command mounts the data dir on your local filesystem to /app/data in the container. So to save the credential via the CLI, try specifying the saved file name like this:
`ssikit vc issue -i did:key:z6MkrNhdvrsyBUSsioTnbr9W1iJGT49XxpoNQgShRCqfUmWM -s did:key:z6MkiFRREdnq6wcDoHA4cYnavgXfG9s9sJY8pTrxX9cuWdro -t VerifiableId /app/data/temp.json`

Then you should find the file in your data folder on the local filesystem.

**Comment by laserguy** [comment]
Thanks, it works now. This update should also be made in the walt.id docs.

**Just one more issue:** 
I'm trying this rest-api : `https://core.ssikit.walt.id/v1/vc/create`

This is my request-body
_{
    "issuerDid": "did:key:z6MkeuYAMTUSmZW3ypomHBgWDWGaGREjcY7MTBWmNiFedwi2",
    "subjectDid": "did:key:z6Mki5fSqS33Nyq9jGNKPkesyTapXpJm5m91BrR66EeEFiPr",
    "templateId": "UniversityDegree"
}_

Response here is similar : 
_{
  "details": [],
  "status": 500,
  "title": " Unknown server error",
  "type": null
}_

I'm following exactly how it's mentioned in the docs: [create-cred](https://docs.walt.id/v/ssikit/getting-started/rest-apis/core-api#create-credential)
