### ISSUE TITLE
Unable to issue a credential file with ssikit vc issue

### ISSUE THREAD

**Issue by vgonisanz** [walt-id/waltid-ssikit#296]
Hi

I'm using the project to test how it works. I'm using the cli using the docker container.

After generate some DIDs and running the following command:

`ssikit vc issue -i ${ISSUER_DID} -s ${HOLDER_DID} -t VerifiableId --interactive`

or this one

`ssikit vc issue -i ${ISSUER_DID} -s ${HOLDER_DID} -t VerifiableId --interactive credential.json`

The output shows the credential created, but it is not stored to a file.
Indeed, the file is created inside the docker, relative to the script that generate it.
It is generated if I append `data/vc/created` to the filename `credential.json`.

In any case, I cannot list the credentials with `ssikit vc list`
and I cannot test a presentation with `ssikit vc present --holder-did ${HOLDER_DID} --verifier-did ${VERIFIER_DID}` command.

Is it a problem with the way I am using it or is this functionality still undone?

**Comment by severinstampler** [comment]
If you use the docker like explained in the ssikit docu:
`alias ssikit="docker container run -p 7000-7004:7000-7004 -itv $(pwd)/data:/app/data docker.io/waltid/ssikit"`
it mounts the local data directory into the container, and therefore if you specify any path in the data subfolder, the credential will be stored on your local disk. Otherwise the credential will be stored in the temporary and virtual filesystem of the container, which is destroyed when the container stops.
You can of course extend the docker command to mount other additional volumes if you need to.
 
As for the `ssikit vc list` command: It lists only credentials that are stored in your custodial credential store. By issuing a credential it is not stored in the custodial store. It is not required to store it there, if you just want to make a presentation, however, you can store the credential using the `ssikit vc import` command, then it will also be listed by the list command.

To present the credential, just specify the path to the credential at the end of the present command. The credential doesn't have to be in the custodian store. But remember, that using the docker command, the credential must be issued to a path, that is mounted as a volume in the container, otherwise it will be lost after the container stops. Eg.:

`ssikit vc issue -i ${ISSUER_DID} -s ${HOLDER_DID} -t VerifiableId --interactive data/my-issued-credential.json`
`ssikit vc present --holder-did ${HOLDER_DID} --verifier-did ${VERIFIER_DID} data/my-issued-credential.json`

**Comment by vgoni-veridas** [comment]
Just for the record: With different commands the relative path can change if the alias is used. Using the docker as instance seems to work fine. You can close the issue. Thanks.
