### ISSUE TITLE
Issuer metadata discovery

### ISSUE THREAD

**Issue by ejossev** [walt-id/waltid-ssikit#333]
Hi,

I'm working on an OIDC4VCI stack, and I've been playing around with this kit while looking for an OIDC4VCI client to test with. I noticed that the kit is looking for issuer metadata in `.well-known/openid-configuration`, while in the OIDC4VCI draft the right place to look for it shall be `.well-known/openid-credential-issuer` (see [here](https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#section-10.2.2)).
My interpretation of the OIDC specs is, that

1. some of the metainformation are related to the OpenID provider, and that shall be in `.well-known/openid-configuration`
2. and some are related to the issuer, and those shall be in `.well-known/openid-credential-issuer`,

i.e. provider and issuer are two disjunct roles, and their metadata are in different locations.

What is your view on that?

**Comment by mikeplotean** [comment]
Hi, the oidc4ci implementation in ssikit is quite old, it is currently being updated to the latest specification - oid4vc - and will include both the oid4vci and oid4vp.
Otherwise, indeed the authorization service metadata are discoverable through `.well-known/openid-configuration`, while the issuer service - through `.well-known/openid-credential-issuer`.
