### ISSUE TITLE
Missing dependency waltid-ssikit v1.2308021811.0

### ISSUE THREAD

**Issue by Tillaert** [walt-id/waltid-ssikit#334]
When importing id.walt/waltid-ssikit version v1.2308021811.0 fails importing:

Error building classpath. Unable to resolve org.webjars.npm/babel__highlight version: [8.0.0-alpha.1,9)

**Comment by Tillaert** [comment]
It is related to this https://stackoverflow.com/questions/76943471/clojure-deps-edn-not-resolving-dependency/76949542#76949542

Javalin has dependencies on npm modules, which use version ranges. One of those version ranges includes an unreleased module. Clojure always picks the newest, and thus tries to resolve a depenency which is not available and fails.

**Comment by mikeplotean** [comment]
Hi, could you provide some reproduction steps?
I'm not familiar with clojure, but here's what I did - created an empty project, set the dependency list and ran the project:
1. `clj -Tnew scratch :name issue334`
2. updated `deps.edn` with the content from [stackoverflow-post](https://stackoverflow.com/questions/76943471/clojure-deps-edn-not-resolving-dependency)
3. `clj`

The project structure looks like the following:
.
├── deps.edn
└── src
&emsp;&emsp;&nbsp;└── scratch.clj
1 directory, 2 files

The output showed no errors when downloading dependencies:
[clojure-output.txt](https://github.com/walt-id/waltid-ssikit/files/12649716/clojure-output.txt)

I assume the build was successful, since I was able to run commands.

**Comment by Tillaert** [comment]
I think the missing dependency got released, resolving the issue.
